config/routes.rb
Rails.application.routes.draw do
  get "/register/", to: "users#new", as: "register"
  post "/register/", to: "users#create", as: "register_post"

  get "/signin", to: "user_sessions#new", as: "signin"
  post "/signin", to: "user_sessions#create", as: "signin_post"
  delete "/signout", to: "user_sessions#destroy", as: "signout"

  scope "/app" do
    resources :produsens do
      resources :furnitures, shallow: true
    end

    resources :transaksis, only: [:index, :show, :create, :update, :destroy]

    resources :users, only: [:index, :show, :edit, :update, :destroy]

    get "/profile", to: "pages#profile", as: "profile"
  end
  get "/app", to: "produsens#index", as: "dashboard"

  get "/sign", to: "pages#index", as: "sign"

  root "produsens#index"
end

app/models/produsen.rb
class Produsen < ApplicationRecord
    validates :name, :description, presence: true
    has_many :furnitures
end

app/controllers/produsens_controller.rb
class ProdusensController < ApplicationController
    before_action :require_login, only: [:show]

    before_action :set_produsen, only: [:show, :edit, :update, :destroy]

    def index
        @produsens = Produsen.all
    end

    def show
    end

    def new
        @produsen = Produsen.new
    end

    def edit
    end

    def create
        @produsen = Produsen.new(produsen_params)

        respond_to do |format|
        if @produsen.save
            format.html { redirect_to @produsen, notice: "produsen was successfully created." }
            format.json { render :show, status: :created, location: @produsen }
        else
            format.html { render :new }
            format.json { render json: @produsen.errors, status: :unprocessable_entity }
        end
        end
    end

    def updated
        respond_to do |format|
        if @produsen.update(produsen_params)
            format.html { redirect_to @produsen, notice: "produsen was successfully updated." }
            format.json { render :show, status: :ok, location: @produsen }
        else
            format.html { render :edit }
            format.json { render json: @produsen.errors, status: :unprocessable_entity }
        end
        end
    end

    def destroy
        @produsen.destroy
        respond_to do |format|
            format.html { redirect_to produsens_url, notice: "produsen was successfully destroyed." }
            format.json { head :no_content }
        end
    end

    private

        def set_produsen
            @produsen = Produsen.find(params[:id])
        end

        def produsen_params
            filtered_params.slice(:name, :description)
      end
end

app/helpers/produsen_helper.rb
module ProdusenHelper
end

app/views/produsens/_form.html.erb
<%= form_with(model: produsen, local: true) do |form| %>
  <% if produsen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produsen.errors.count, "error") %> prohibited this produsen from being saved:</h2>

      <ul>
      <% produsen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/produsens/edit.html.erb
<h1>Editing Produsen</h1>

<%= render 'form', produsen: @produsen %>

<%= link_to 'Show', @produsen %> |
<%= link_to 'Back', produsens_path %>

app/views/produsens/index.html.erb
<% content_for :page_title do %>
  Furnitures
<% end %>

<% content_for :page_header do %>
  <%= render 'pages/header' %>
<% end %>

<% content_for :page_content do %>
  <div class="slider">
    <ul class="slides">
      <li>
        <img src="https://images.pexels.com/photos/545012/pexels-photo-545012.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"> <!-- random image -->
        <div class="caption center-align">
          <h3>Find your sleep essentials!</h3>
          <h5 class="light grey-text text-lighten-3">Sleep better with furnish.</h5>
        </div>
      </li>
      <li>
        <img src="https://images.pexels.com/photos/707196/pexels-photo-707196.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940">
        <div class="caption center-align">
          <h3>Boost your study moods</h3>
          <h5 class="light grey-text text-lighten-3">Study better with furnish.</h5>
        </div>
      </li>
      <li>
        <img src="https://images.pexels.com/photos/133919/pexels-photo-133919.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"> 
        <div class="caption center-align">
          <h3>Be profesionalls couch potato</h3>
          <h5 class="light grey-text text-lighten-3">Relax better with furnish.</h5>
        </div>
      </li>
    </ul>
  </div>

  <div class="divider"></div>

  <div class="container">
    <% @produsens.each_slice(2) do |produsens|%>
      <div class="row">
        <% produsens.each do |produsen|%>
          <div class="col s6">
            <div class="card">
              <div class="card-image waves-effect waves-block waves-light">
                <img class="activator" src="https://article.images.consumerreports.org/prod/content/dam/CRO%20Images%202018/Magazine/08August/CR-Magazine-Inlinehero-qanda-list-items-home-insurance-August-2018-0618">
              </div>
              <div class="card-content">
                <span class="card-title activator grey-text text-darken-4"><%= produsen.name %><i class="material-icons right">more_vert</i></span>
                <p><a href="" onclick="location.href='<%= produsen_path(produsen) %>'">see calatog</a></p>
              </div>
              <div class="card-reveal">
                <span class="card-title grey-text text-darken-4"> Description <i class="material-icons right">close</i></span>
                <p><%= produsen.description %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div> 
<% end %>

<%= render template: "layouts/pages" %>

app/views/produsens/show.html.erb
<% content_for :page_title do %>
  Furnitures
<% end %>

<% content_for :page_header do %>
  <%= render 'pages/header' %>
<% end %>

<% content_for :page_content do %>
    <section id="content">
        <div class="container">
            <div class="card-panel">
                <div class="row">
                    <div class="col s12">
                        <h4><%= @produsen.name %></h4>
                        <p><%= @produsen.description %></p>
                    </div>
                </div>
                <div class="row">
                </div>
            </div>
            <%= render partial: 'transaksis/form', locals: { transaksi: Transaksi.new, produsen: @produsen } %>
        </div>
    </section>
<% end %>

<%= render template: "layouts/pages" %>