config/routes.rb
Rails.application.routes.draw do
  get "/register/", to: "users#new", as: "register"
  post "/register/", to: "users#create", as: "register_post"

  get "/signin", to: "user_sessions#new", as: "signin"
  post "/signin", to: "user_sessions#create", as: "signin_post"
  delete "/signout", to: "user_sessions#destroy", as: "signout"

  scope "/app" do
    resources :produsens do
      resources :furnitures, shallow: true
    end

    resources :transaksis, only: [:index, :show, :create, :update, :destroy]

    resources :users, only: [:index, :show, :edit, :update, :destroy]

    get "/profile", to: "pages#profile", as: "profile"
  end
  get "/app", to: "produsens#index", as: "dashboard"

  get "/sign", to: "pages#index", as: "sign"

  root "produsens#index"
end

app/views/pages/_header.html.erb
<header id="header" class="page-topbar">
    <!-- start header nav-->
    <div class="navbar-fixed">
        <ul id="dropdown1" class="dropdown-content">
            <li><a href="#!">My Profile</a></li>
            <li><a href="#!">History</a></li>
            <li class="divider"></li>
        </ul>
        <nav class="navbar-color grey darken-4">
            <div class="nav-wrapper">
                <a href="<%= dashboard_path %>" class="brand-logo center">furnish.</a>
                <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">reorder</i></a>
                <ul id="nav-mobile" class="left hide-on-med-and-down">
                    <% if logged_in? %>
                        <% if current_user.admin?%>
                            <li><a href="<%= transaksis_path %>">All Transactions</li>
                        <% elsif current_user.customer? %>
                            <li><a href="<%= transaksis_path %>">My Cart</li>
                        <% end %>
                    <% end %>
                </ul>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                <% if logged_in?%>
                    <li><a class="dropdown-trigger" href="#!" data-target="dropdown1"><%= current_user.username %></a></li>
                    <li><%= link_to "SIGN OUT", signout_path, class: "btn waves-effect waves-blue white light-blue-text text-darken-4", id: "signout", method: "delete" %></li>
                <% else %>
                    <li>
                        <%= link_to "SIGN IN", sign_path, class: "btn waves-effect waves-blue white light-blue-text text-darken-4", id: "signin" %>
                    </li>
                <% end %>
                </ul>
            </div>
        </nav>
        <ul class="sidenav" id="mobile-demo">
            <li><a href="https://www.google.com/">Shop</a></li>
            <li><a href="#">Catalog</a></li>
            <li><a href="#">Contact</a></li>
        </ul> 
    </div>
    <!-- end header nav-->
</header>

app/views/pages/index.html.erb
<% content_for :title do %>
  Welcome
<% end %>

<% content_for :content do %>
    <div class="landing-content">
        <div class="landing-container">
            <h1 class="landing-heading white-text">
            <i class="fa fa-home"></i>furnish.
            </h1>
            <div class="landing-links-container">
            <%= link_to "JOIN US!", register_path(), class: "btn waves-effect waves-light light-blue darken-4", id: "register-user" %>
            <%= link_to "SIGN IN", signin_path, class: "btn waves-effect waves-red white light-blue-text text-darken-4", id: "login" %>
            </div>
        </div>
    </div>
<% end %>