config/routes.rb
Rails.application.routes.draw do
  get "/register/", to: "users#new", as: "register"
  post "/register/", to: "users#create", as: "register_post"

  get "/signin", to: "user_sessions#new", as: "signin"
  post "/signin", to: "user_sessions#create", as: "signin_post"
  delete "/signout", to: "user_sessions#destroy", as: "signout"

  scope "/app" do
    resources :produsens do
      resources :furnitures, shallow: true
    end

    resources :transaksis, only: [:index, :show, :create, :update, :destroy]

    resources :users, only: [:index, :show, :edit, :update, :destroy]

    get "/profile", to: "pages#profile", as: "profile"
  end
  get "/app", to: "produsens#index", as: "dashboard"

  get "/sign", to: "pages#index", as: "sign"

  root "produsens#index"
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_logout, only: [:new, :create]
  
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params)

    if @user_session.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def destroy
    current_user_session.destroy
    redirect_to dashboard_path
  end

  private

    def user_session_params
      params.require(:user_session).permit(:username, :password).to_h
    end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_with(model: user_session, url: signin_post_path, local: true) do |form| %>
  <div class="input-field">
    <i class="material-icons prefix">person_outline</i>
    <%= form.label :username %>
    <%= form.text_field :username %>
    <% if user_session.errors[:username].any? %>
      <small class="red-text"><%= user_session.errors.full_messages_for(:username).first %></small>
    <% end %>
  </div>

  <div class="input-field">
  <i class="material-icons prefix">lock_outline</i>
    <%= form.label :password %>
    <%= form.password_field :password %>
    <% if user_session.errors[:password].any? %>
      <small class="red-text"><%= user_session.errors.full_messages_for(:password).first %></small>
    <% end %>
  </div>

  <div class="actions">
    <%= form.button "Signin", type: :submit, class: "btn waves-effect waves-light light-blue darken-4 white-text"  %>
  </div>
  <%= link_to "Register Here", register_path, class: "waves-effect waves-light btn-small white light-blue-text text-darken-4", id:"static-page" %>
<% end %>

app/views/user_sessions/new.html.erb
<% content_for :title do %>
  Sign in
<% end %>

<div class="login-content">
  <div class="login-container card hoverable">
    <div class="login-heading">
      <h2 class="login-heading-logo light-blue-text text-darken-4">
        <i class="fa fa-home"></i>furnish.
      </h2>
      <h4 class="login-heading-title">SIGN IN</h4>
    </div>
    <div class="login-form">
      <%= render 'form', user_session: @user_session %>
    </div>
  </div>
</div>

<% content_for :scripts do %>
  <script>
  </script>
<% end %>